# Conda Environment for Linus and MacOS

name: learn_fortran
channels:
  - conda-forge
dependencies:
  - pip
  - fortls
  - fpm
  - gfortran
  - git
  - lfortran
  - pip:
      - findent
      - fprettify
