# Conda Environment for Windows PC

name: learn_fortran
channels:
  - conda-forge
dependencies:
  - pip
  - fortls
  - fpm
  - git
  - lfortran
  - m2w64-gcc-fortran # https://github.com/msys2/MINGW-packages/discussions/12013
  - pip:
      - findent
      - fprettify
